name: Deploy client
on:
  push:
    branches: [main]
    paths:
      - 'apps/client/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 22.9.0

      - name: Install npm dependencies
        run: npm i -g pnpm && pnpm install

      - name: 'Build and deploy client'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/client'
          wranglerVersion: '4.8.0'
          packageManager: pnpm
          preCommands: 'pnpm build'
